update lein

diff --git a/bin/lein b/bin/lein
--- a/bin/lein
+++ b/bin/lein
@@ -1,20 +1,13 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-LEIN_VERSION="1.6.2"
-export LEIN_VERSION
+export LEIN_VERSION="2.0.0-preview7"
 
 case $LEIN_VERSION in
     *SNAPSHOT) SNAPSHOT="YES" ;;
     *) SNAPSHOT="NO" ;;
 esac
 
-# Make sure classpath is in unix format for manipulating, then put
-# it back to windows format when we use it
-if [ "$OSTYPE" = "cygwin" ] && [ "$CLASSPATH" != "" ]; then
-    CLASSPATH=`cygpath -up $CLASSPATH`
-fi
-
-if [ `whoami` = "root" ] && [ "$LEIN_ROOT" = "" ]; then
+if [ `id -u` -eq 0 ] && [ "$LEIN_ROOT" = "" ]; then
     echo "WARNING: You're currently running as root; probably by accident."
     echo "Press control-C to abort or Enter to continue as root."
     echo "Set LEIN_ROOT to disable this warning."
@@ -32,55 +25,13 @@ do
     fi
 done
 
-if [ "$LEIN_HOME" = "" ]; then
-  if [ -d "$PWD/.lein" ] && [ "$PWD" != "$HOME" ]; then
-    echo "Leiningen is running in bundled mode."
-    LEIN_HOME="$PWD/.lein"
-  else
-    LEIN_HOME="$HOME/.lein"
-  fi
+export LEIN_HOME=${LEIN_HOME:-"$HOME/.lein"}
+
+if [ "$OSTYPE" = "cygwin" ]; then
+    export LEIN_HOME=`cygpath -w $LEIN_HOME`
 fi
 
-DEV_PLUGINS="$(ls -1 lib/dev/*jar 2> /dev/null)"
-USER_PLUGINS="$(ls -1 "$LEIN_HOME"/plugins/*jar 2> /dev/null)"
-
-artifact_name () {
-    echo "$1" | sed -e "s/.*\/\(.*\)/\1/" | \
-        rev | sed -e "s/raj[-[:digit:].]*-\(.*\)/\1/" | rev
-}
-
-unique_user_plugins () {
-    saveIFS="$IFS"
-    IFS="$(printf '\n\t')"
-
-    plugins="$(echo "$DEV_PLUGINS"; echo "$USER_PLUGINS")"
-    artifacts="$(for i in $plugins; do echo "$(artifact_name "$i")"; done)"
-    duplicates="$(echo "$artifacts" | sort | uniq -d)"
-
-    if [ -z "$duplicates" ]; then
-        echo "$USER_PLUGINS"
-    else
-        for i in $USER_PLUGINS; do
-            artifact="$(artifact_name "$i")"
-            if ! echo "$duplicates" | grep -xq "$artifact"; then
-                echo "$i"
-            fi
-        done
-    fi
-    IFS="$saveIFS"
-}
-
-LEIN_PLUGIN_PATH="$(echo "$DEV_PLUGINS" | tr \\n :)"
-LEIN_USER_PLUGIN_PATH="$(echo "$(unique_user_plugins)" | tr \\n :)"
-CLASSPATH="$CLASSPATH:$LEIN_PLUGIN_PATH:$LEIN_USER_PLUGIN_PATH:test/:src/:resources/"
 LEIN_JAR="$LEIN_HOME/self-installs/leiningen-$LEIN_VERSION-standalone.jar"
-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.2.1/clojure-1.2.1.jar"
-NULL_DEVICE=/dev/null
-
-# apply context specific CLASSPATH entries
-if [ -f .lein-classpath ]; then
-    CLASSPATH="`cat .lein-classpath`:$CLASSPATH"
-fi
 
 # normalize $0 on certain BSDs
 if [ "$(dirname "$0")" = "." ]; then
@@ -102,41 +53,85 @@ done
 
 BIN_DIR="$(dirname "$SCRIPT")"
 
-if [ -r "$BIN_DIR/../src/leiningen/core.clj" ]; then
+if [ -r "$BIN_DIR/../src/leiningen/version.clj" ]; then
     # Running from source checkout
     LEIN_DIR="$(dirname "$BIN_DIR")"
-    LEIN_LIBS="$(find -H "$LEIN_DIR/lib" -mindepth 1 -maxdepth 1 -print0 2> /dev/null | tr \\0 \:)"
-    CLASSPATH="$CLASSPATH:$LEIN_LIBS:$LEIN_DIR/src:$LEIN_DIR/classes:$LEIN_DIR/resources:$LEIN_JAR"
 
-    if [ "$LEIN_LIBS" = "" -a "$1" != "self-install" -a ! -r "$LEIN_JAR" ]; then
-        echo "Leiningen is missing its dependencies. Please see \"Building\" in the README."
+    # Need to use lein 1.x to bootstrap the leiningen-core library (for aether)
+    if [ "$(ls $LEIN_DIR/leiningen-core/lib/*)" = "" ]; then
+        echo "Leiningen is missing its dependencies."
+        echo "Please see \"Building\" in the README."
         exit 1
     fi
-else
-    # Not running from a checkout
-    CLASSPATH="$CLASSPATH:$LEIN_JAR"
+
+    # If project.clj for lein or leiningen-core changes, we must recalculate
+    LAST_PROJECT_CHECKSUM=$(cat "$LEIN_DIR/.lein-project-checksum" 2> /dev/null)
+    PROJECT_CHECKSUM=$(sum "$LEIN_DIR/project.clj" "$LEIN_DIR/leiningen-core/project.clj")
+    if [ "$PROJECT_CHECKSUM" != "$LAST_PROJECT_CHECKSUM" ]; then
+        if [ -r "$LEIN_DIR/.lein-classpath" ]; then
+            rm "$LEIN_DIR/.lein-classpath"
+        fi
+    fi
+
+    # Use bin/lein to calculate its own classpath since src/ and
+    # leiningen-core/lib/*jar suffices to run the classpath task.
+    if [ ! -r "$LEIN_DIR/.lein-classpath" ] && [ "$1" != "classpath" ]; then
+        echo "Recalculating Leiningen's classpath."
+        ORIG_PWD="$PWD"
+        cd "$LEIN_DIR"
+
+        $0 classpath .lein-classpath
+        sum $LEIN_DIR/project.clj $LEIN_DIR/leiningen-core/project.clj > \
+            .lein-project-checksum
+        cd "$ORIG_PWD"
+    fi
+
+    mkdir -p "$LEIN_DIR/target/classes"
+    export LEIN_JVM_OPTS=${LEIN_JVM_OPTS:-"-Dclojure.compile.path=$LEIN_DIR/target/classes"}
+    CLASSPATH="$LEIN_DIR/leiningen-core/src/"
+    CLASSPATH="$CLASSPATH:$LEIN_DIR/leiningen-core/resources/"
+    CLASSPATH="$CLASSPATH:$(cat $LEIN_DIR/.lein-classpath 2> /dev/null)"
+    CLASSPATH="$CLASSPATH:$LEIN_DIR/leiningen-core/lib/*"
+    CLASSPATH="$CLASSPATH:$LEIN_DIR/test:$LEIN_DIR/target/classes"
+    CLASSPATH="$CLASSPATH:$LEIN_DIR/src:$LEIN_DIR/resources:$LEIN_JAR"
+    if [ -f .lein-classpath ]; then
+        CLASSPATH="`cat .lein-classpath`:$CLASSPATH"
+    fi
+else # Not running from a checkout
+    # apply context specific CLASSPATH entries
+    if [ -f .lein-classpath ]; then
+        CLASSPATH="`cat .lein-classpath`:$LEIN_JAR"
+    else
+        CLASSPATH="$LEIN_JAR"
+    fi
+
+    export LEIN_JVM_OPTS=${LEIN_JVM_OPTS:-"-Xbootclasspath/a:$LEIN_JAR"}
 
     if [ ! -r "$LEIN_JAR" -a "$1" != "self-install" ]; then
         "$0" self-install
     fi
 fi
 
-HTTP_CLIENT="wget --no-check-certificate -O"
-if type -p curl >/dev/null 2>&1; then
-    if [ "$https_proxy" != "" ]; then
-        CURL_PROXY="-x $https_proxy"
+if [ "$HTTP_CLIENT" = "" ]; then
+    if type -p curl >/dev/null 2>&1; then
+        if [ "$https_proxy" != "" ]; then
+            CURL_PROXY="-x $https_proxy"
+        fi
+        HTTP_CLIENT="curl $CURL_PROXY -f -L -o"
+    else
+        HTTP_CLIENT="wget -O"
     fi
-    HTTP_CLIENT="curl $CURL_PROXY --insecure -f -L -o"
 fi
 
 export JAVA_CMD=${JAVA_CMD:-"java"}
+export LEIN_JAVA_CMD=${LEIN_JAVA_CMD:-$JAVA_CMD}
 
 # Support $JAVA_OPTS for backwards-compatibility.
-export JVM_OPTS=${JVM_OPTS:-"$JAVA_OPTS"}
+export JVM_OPTS="${JVM_OPTS:-"$JAVA_OPTS"}"
 
 # TODO: investigate http://skife.org/java/unix/2011/06/20/really_executable_jars.html
 # If you're packaging this for a package manager (.deb, homebrew, etc)
-# you need to remove the self-install and upgrade functionality.
+# you need to remove the self-install and upgrade functionality or see lein-pkg.
 if [ "$1" = "self-install" ]; then
     if [ -r "$LEIN_JAR" ]; then
       echo "The self-install jar already exists at $LEIN_JAR."
@@ -150,6 +145,10 @@ if [ "$1" = "self-install" ]; then
     $HTTP_CLIENT "$LEIN_JAR" "$LEIN_URL"
     if [ $? != 0 ]; then
         echo "Failed to download $LEIN_URL"
+        echo "If you have an old version of libssl you may not have the correct"
+        echo "certificate authority. Either upgrade or set HTTP_CLIENT to insecure:"
+        echo "  export HTTP_CLIENT=\"wget --no-check-certificate -O\" # or"
+        echo "  export HTTP_CLIENT=\"curl --insecure -f -L -o"
         if [ $SNAPSHOT = "YES" ]; then
             echo "If you have Maven installed, you can do"
             echo "mvn dependency:copy-dependencies; mv target/dependency lib"
@@ -172,7 +171,8 @@ elif [ "$1" = "upgrade" ]; then
         echo "You do not have permission to upgrade the installation in $SCRIPT"
         exit 1
     else
-        echo "The script at $SCRIPT will be upgraded to the latest stable version."
+        TARGET_VERSION="${2:-"preview"}"
+        echo "The script at $SCRIPT will be upgraded to the latest $TARGET_VERSION version."
         echo -n "Do you want to continue [Y/n]? "
         read RESP
         case "$RESP" in
@@ -180,7 +180,10 @@ elif [ "$1" = "upgrade" ]; then
                 echo
                 echo "Upgrading..."
                 TARGET="/tmp/lein-$$-upgrade"
-                LEIN_SCRIPT_URL="https://github.com/technomancy/leiningen/raw/stable/bin/lein"
+                if [ "$OSTYPE" = "cygwin" ]; then
+                    TARGET=`cygpath -w $TARGET`
+                fi
+                LEIN_SCRIPT_URL="https://github.com/technomancy/leiningen/raw/$TARGET_VERSION/bin/lein"
                 $HTTP_CLIENT "$TARGET" "$LEIN_SCRIPT_URL" \
                     && mv "$TARGET" "$SCRIPT" \
                     && chmod +x "$SCRIPT" \
@@ -194,66 +197,36 @@ elif [ "$1" = "upgrade" ]; then
 else
     if [ "$OSTYPE" = "cygwin" ]; then
         # When running on Cygwin, use Windows-style paths for java
-        CLOJURE_JAR=`cygpath -w "$CLOJURE_JAR"`
         ORIGINAL_PWD=`cygpath -w "$ORIGINAL_PWD"`
         CLASSPATH=`cygpath -wp "$CLASSPATH"`
-        NULL_DEVICE=NUL
     fi
 
     if [ $DEBUG ]; then
-        echo $CLASSPATH
-        echo $CLOJURE_JAR
+        echo "Classpath: $CLASSPATH"
     fi
 
-    JLINE=""
-    if ([ "$1" = "repl" ] || [ "$1" = "interactive" ] || [ "$1" = "int" ]) &&
-        [ -z $INSIDE_EMACS ] && [ "$TERM" != "dumb" ]; then
-        # Use rlwrap if it's available, otherwise fall back to JLine
-        RLWRAP=`which rlwrap`
-        if [ ! -x "$RLWRAP" ] || [ "$RLWRAP" = "" ]; then
-            if [ ! -r "$LEIN_HOME/.jline-warn" ]; then
-                echo "Using JLine for console I/O; install rlwrap for optimum experience."
-                touch "$LEIN_HOME/.jline-warn"
-            fi
-            RLWRAP=""
-            JLINE=jline.ConsoleRunner
-            if [ "$OSTYPE" = "cygwin" ]; then
-                JLINE="-Djline.terminal=jline.UnixTerminal jline.ConsoleRunner"
-                CYGWIN_JLINE=y
-            fi
-        else
-            # Test to see if rlwrap supports custom quote chars
-            rlwrap -m -q '"' echo "hi" > /dev/null 2>&1
-            if [ $? -eq 0 ]; then
-                RLWRAP="$RLWRAP -r -m -q '\"'"
-            fi
-        fi
+    TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
+    if [ "$OSTYPE" = "cygwin" ]; then
+        TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
     fi
 
-    # The -Xbootclasspath argument is optional here: if the jar
-    # doesn't exist everything will still work, it will just have a
-    # slower JVM boot.
-    test $CYGWIN_JLINE && stty -icanon min 1 -echo
-    if [ "$1" = "trampoline" ]; then
-        TRAMPOLINE_FILE="/tmp/lein-trampoline-$$"
-        if [ "$OSTYPE" = "cygwin" ]; then
-            TRAMPOLINE_FILE=`cygpath -w $TRAMPOLINE_FILE`
-        fi
-        $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client \
-            $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-            -Dleiningen.trampoline-file=$TRAMPOLINE_FILE -cp "$CLASSPATH" \
-            $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
-            $NULL_DEVICE "$@"
-        if [ -r $TRAMPOLINE_FILE ]; then
-            TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
-            rm $TRAMPOLINE_FILE
-            exec sh -c "exec $TRAMPOLINE"
-        fi
+    $LEIN_JAVA_CMD \
+        -client -XX:+TieredCompilation \
+        $LEIN_JVM_OPTS \
+        -Dfile.encoding=UTF-8 \
+        -Dmaven.wagon.http.ssl.easy=false \
+        -Dleiningen.original.pwd="$ORIGINAL_PWD" \
+        -Dleiningen.trampoline-file=$TRAMPOLINE_FILE \
+        -cp "$CLASSPATH" \
+        clojure.main -m leiningen.core.main "$@"
+
+    EXIT_CODE=$?
+
+    if [ -r $TRAMPOLINE_FILE ]; then
+        TRAMPOLINE="$(cat $TRAMPOLINE_FILE)"
+        rm $TRAMPOLINE_FILE
+        exec sh -c "exec $TRAMPOLINE"
     else
-        exec $RLWRAP $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client \
-            $LEIN_JVM_OPTS -Dleiningen.original.pwd="$ORIGINAL_PWD" \
-            -cp "$CLASSPATH" $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
-            $NULL_DEVICE "$@"
+        exit $EXIT_CODE
     fi
-    test $CYGWIN_JLINE && stty icanon echo
 fi
